---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-nova-az2
data:
  03-ceph-nova.conf: _replaced_
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova-custom-ceph-az2
spec:
  caCerts: combined-ca-bundle
  dataSources:
    - configMapRef:
        name: ceph-nova-az2
    - configMapRef:
        name: nova-extra-config-az2
    - secretRef:
        name: nova-cell3-compute-config
    - secretRef:
        name: nova-migration-ssh-key
  edpmServiceType: nova
  label: dataplane-deployment-nova-custom-ceph-az2
  playbook: osp.edpm.nova
  tlsCerts:
    default:
      contents:
        - dnsnames
        - ips
      edpmRoleServiceName: nova
      issuer: osp-rootca-issuer-internal
      networks:
        - ctlplane
